apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: 681424868466.dkr.ecr.ap-south-1.amazonaws.com/vijay-ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-svc
spec:
  selector:
    app: javaapp
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
