apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploypod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebapp
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: demoappdeploy
        image: 681424868466.dkr.ecr.ap-south-1.amazonaws.com/vijay-ecr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
